### ISSUE TITLE
Corregir texto de presentación del website

### ISSUE THREAD

**Issue by fedecatinello** [BlackBoxVision/blackbox-vision.io#18]
El texto que se muestra en el título no esta del todo bien traducido al idioma inglés, o tiene algunos errores en su formulación.

"Let's Make your projects come true
Let us make the hardest part for you and get the product you were looking for"

**Comment by JonatanSalas** [comment]
this is almost done.-

**Comment by JonatanSalas** [comment]
@fedecatinello it's not deployed yet. I will deploy it, when all issues here are solved.
